name: Release Build

on:
  push:
    tags:
      - 'v*'  # 当推送以 v 开头的标签（如 v1.0.0）时触发

permissions:
  contents: write  # 允许发布 Release

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, windows-latest]
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          override: true

      - name: Build Release
        run: cargo build --release

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: tiling-gallery-${{ matrix.os }}
          path: target/release/tiling-gallery${{ matrix.os == 'windows-latest' && '.exe' || '' }}

  create-release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download macOS Artifact
        uses: actions/download-artifact@v4
        with:
          name: tiling-gallery-macos-latest
          path: artifacts/macos

      - name: Download Windows Artifact
        uses: actions/download-artifact@v4
        with:
          name: tiling-gallery-windows-latest
          path: artifacts/windows

      - name: List downloaded files (for debugging)
        run: find artifacts -type f

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.ref }}
          files: |
            artifacts/macos/tiling-gallery
            artifacts/windows/tiling-gallery.exe
